### ISSUE TITLE
Rehber'deki bi kayda dokunulduğunda kaydın numarasının textbox'a geçmesi lazım.

### ISSUE THREAD

**Issue by burakkarakus** [burakkarakus/BabyBG#1]

**Comment by gokayerim** [comment]
Babycare piyasaya geri mi dönüyor :)

**Comment by burakkarakus** [comment]
hahah olm repolarda geziyodum baktım bitirdiğimiz issue varmış dedim açık
kalmasın kapatayım :D

_Burak Karakuş__oBilet Bilişim Sistemleri A.Ş._

Tel: +90 506 778 87 07 <%2B90%20531%20973%2078%2073>

burak@obilet.com | www.obilet.com

http://www.obilet.com/

2016-06-03 18:23 GMT+03:00 Gokay notifications@github.com:

**Comment by gokayerim** [comment]
Aslinda ufak bir plan yapip arayüzü felan elden geçirip birşeyler yapılabilir.  Ben haftasonu bir bakayım evden adam edebilirmiyiz.  Birşeyler artik daha kafada oturdu gibi voice transfer olmayacak is degil whatsappinki gibi birsey yapilabilir 10 saniyelik data kaydedip local network üzerinden yollanmasi gibi bir konuşalım şunu :))

**Comment by burakkarakus** [comment]
ulan ben bunu görmemişim. ok aga ben de yarın gün içinde bi bakayım, hem
android studio'da stabil hale geldi artık eclipse te anamız ağlamaz :p
java'da göçtüm ben iyice biraz tazelemiş olurum hem.

_Burak Karakuş__oBilet Bilişim Sistemleri A.Ş._

Tel: +90 506 778 87 07 <%2B90%20531%20973%2078%2073>

burak@obilet.com | www.obilet.com

http://www.obilet.com/

3 Haziran 2016 18:37 tarihinde Gokay notifications@github.com yazdı:
